//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class citasMedicas
    {
        public string codCita { get; set; }
        public string codPaciente { get; set; }
        public string codMedico { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public string hora { get; set; }
    }
}
